add_newline = false

[git_status]
disabled = true

[git_branch]
symbol = "ğŸŒ± "

[package]
disabled = true

[character]
#success_symbol = "[âœ ](bold green)"
# success_symbol = "[ğŸ ](bold green)"

# format = """
# [â”‚](bold green)
# [â””> ğŸ ](bold green) """

# format = """
# [â””> ](bold green) """

# format = """
# [ğŸ âœ ](bold green) """
format = """
[âœ ](bold green) """
