add_newline = true

[git_status]
disabled = true

[git_branch]
symbol = "ðŸŒ± "

[character]
#success_symbol = "[âžœ ](bold green)"
# success_symbol = "[ðŸ ](bold green)"
# format = """
# [â”‚](bold green)
# [â””> ðŸ ](bold green) """
format = """
[â””> ](bold green) """
